# Generated by Django 5.2.4 on 2025-12-03 04:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='楼栋区域')),
            ],
        ),
        migrations.CreateModel(
            name='AssetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='资产类别')),
            ],
        ),
        migrations.CreateModel(
            name='background',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='上传名称')),
                ('img', models.FileField(max_length=128, upload_to='backgrounds/', verbose_name='文件')),
                ('is_img', models.BooleanField(default=False, verbose_name='是否激活')),
            ],
        ),
        migrations.CreateModel(
            name='Depart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depart_title', models.CharField(max_length=50, verbose_name='部门名称')),
                ('depart_number', models.CharField(default=6, max_length=50, verbose_name='部门人数')),
            ],
        ),
        migrations.CreateModel(
            name='gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='性别')),
            ],
        ),
        migrations.CreateModel(
            name='occupancyrecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_date', models.DateField(verbose_name='入住时间')),
                ('check_out_date', models.DateField(blank=True, null=True, verbose_name='退宿时间')),
                ('status', models.CharField(choices=[('0', '正常'), ('1', '退宿')], default='0', max_length=30, verbose_name='状态(0-正常,1-退宿)')),
            ],
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='权限名称')),
            ],
        ),
        migrations.CreateModel(
            name='Personne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='人员类型')),
            ],
        ),
        migrations.CreateModel(
            name='room_status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='房间状态')),
            ],
        ),
        migrations.CreateModel(
            name='room_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='房间类型')),
                ('bed_count', models.IntegerField(verbose_name='床位数量')),
            ],
        ),
        migrations.CreateModel(
            name='userstatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='用户状态')),
            ],
        ),
        migrations.CreateModel(
            name='dorm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='楼栋名称')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel.area', verbose_name='区域id')),
            ],
        ),
        migrations.CreateModel(
            name='feetype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='计费项目')),
                ('fee', models.CharField(max_length=30, verbose_name='费用单价')),
                ('bit', models.CharField(max_length=30, verbose_name='计算单位')),
                ('is_sign', models.BooleanField(default=False, verbose_name='是否固定')),
                ('status', models.CharField(choices=[('启用', '用'), ('封存', '封')], max_length=30, verbose_name='状态')),
                ('cdate', models.DateField(verbose_name='创建时间')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel.area', verbose_name='区域')),
            ],
        ),
        migrations.CreateModel(
            name='fee_record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=30, verbose_name='计算月份')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, max_length=30, verbose_name='金额')),
                ('status', models.CharField(choices=[('0', '未缴'), ('1', '已缴'), ('2', '部分已缴')], default='0', max_length=30, verbose_name='状态(0-未缴,1-已缴,2-部分已缴)')),
                ('cdate', models.DateField(verbose_name='创建时间')),
                ('check_people', models.CharField(max_length=30, verbose_name='录入人')),
                ('feetype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel.feetype', verbose_name='计费类型')),
            ],
        ),
        migrations.CreateModel(
            name='discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='折扣率(%)')),
                ('date', models.CharField(max_length=30, verbose_name='计算月份')),
                ('fee_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel.feetype', verbose_name='费用类型')),
            ],
        ),
        migrations.CreateModel(
            name='feesharing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feesharings', models.CharField(max_length=30, verbose_name='个人分摊金额')),
                ('status', models.CharField(choices=[('1', '是'), ('0', '否')], max_length=30, verbose_name='是否缴纳(1-是)')),
                ('start_date', models.DateField(verbose_name='开始计费日期')),
                ('end_date', models.DateField(verbose_name='结束计费日期')),
                ('date', models.DateField(blank=True, null=True, verbose_name='缴纳时间')),
                ('fee_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel.fee_record', verbose_name='费用细则')),
                ('fee_type', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hostel.feetype', verbose_name='计费类型')),
                ('occupancyrecord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel.occupancyrecord', verbose_name='住宿记录')),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='初始密码')),
                ('name', models.CharField(blank=True, max_length=30, verbose_name='真实姓名')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='邮箱')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='联系电话')),
                ('is_super', models.BooleanField(default=False, verbose_name='是否超级管理员')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('depart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hostel.depart', verbose_name='所属部门')),
                ('permissions', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='hostel.permission', verbose_name='权限')),
            ],
            options={
                'verbose_name': '管理员',
                'verbose_name_plural': '管理员列表',
                'ordering': ['-create_date'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='名字')),
                ('password', models.CharField(max_length=128, verbose_name='初始密码')),
                ('phone', models.CharField(max_length=30, verbose_name='电话号码')),
                ('money', models.BooleanField(default=True, verbose_name='是否补贴')),
                ('depart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel.depart', verbose_name='部门')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel.gender', verbose_name='性别')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel.permission', verbose_name='权限')),
                ('personne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel.personne', verbose_name='人员类型')),
            ],
        ),
        migrations.AddField(
            model_name='occupancyrecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel.person', verbose_name='员工'),
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=30, verbose_name='房间名称')),
                ('people', models.IntegerField(verbose_name='房间人数')),
                ('dorm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel.dorm', verbose_name='楼栋')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel.gender', verbose_name='性别')),
                ('room_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel.room_status', verbose_name='房间状态')),
                ('room_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hostel.room_type', verbose_name='房间类型')),
            ],
        ),
        migrations.CreateModel(
            name='resource_useage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.CharField(default='89602', max_length=30, verbose_name='月初计数')),
                ('end', models.CharField(default='90002', max_length=40, verbose_name='月底计数')),
                ('usege', models.DecimalField(blank=True, decimal_places=2, max_digits=10, max_length=30, null=True, verbose_name='用量')),
                ('check_in_date', models.DateField(verbose_name='录入日期')),
                ('check_people', models.CharField(max_length=30, verbose_name='录入人')),
                ('feetype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel.feetype', verbose_name='计费类型')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='res', to='hostel.room', verbose_name='房间')),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel.room', verbose_name='房间'),
        ),
        migrations.AddField(
            model_name='occupancyrecord',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel.room', verbose_name='房间id'),
        ),
        migrations.CreateModel(
            name='fee_record_one',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dynamic_fees', models.JSONField(default=dict, verbose_name='动态费用项目')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, max_length=30, verbose_name='总金额')),
                ('status', models.CharField(choices=[('0', '未缴'), ('1', '已缴'), ('2', '部分已缴')], default='0', max_length=30, verbose_name='状态(0-未缴,1-已缴,2-部分已缴)')),
                ('date', models.DateField(max_length=30, verbose_name='计算月份')),
                ('check_people', models.CharField(default='admin', max_length=30, verbose_name='录入人')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel.room', verbose_name='房间')),
            ],
        ),
        migrations.AddField(
            model_name='fee_record',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='hostel.room', verbose_name='房间'),
        ),
        migrations.CreateModel(
            name='fee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, max_length=30, verbose_name='总金额')),
                ('paid', models.DecimalField(decimal_places=2, max_digits=10, max_length=30, verbose_name='已缴金额')),
                ('date', models.DateField(verbose_name='缴纳月份')),
                ('status', models.CharField(choices=[('1', '是'), ('0', '否')], default=1, max_length=30, verbose_name='是否缴纳(0-是,1-否)')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel.room', verbose_name='房间')),
            ],
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_code', models.CharField(max_length=50, unique=True, verbose_name='资产编号')),
                ('name', models.CharField(max_length=100, verbose_name='资产名称')),
                ('brand', models.CharField(blank=True, max_length=100, verbose_name='品牌')),
                ('model', models.CharField(blank=True, max_length=100, verbose_name='型号')),
                ('purchase_date', models.DateField(verbose_name='购买日期')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='购买价格')),
                ('status', models.CharField(choices=[('normal', '正常'), ('repairing', '维修中'), ('scrapped', '已报废')], default='normal', max_length=20, verbose_name='状态')),
                ('bound_at', models.DateTimeField(auto_now_add=True, verbose_name='绑定时间')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel.assetcategory', verbose_name='资产类别')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='hostel.room', verbose_name='所属宿舍')),
            ],
        ),
        migrations.CreateModel(
            name='sharing2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.JSONField(default=dict, verbose_name='分摊明细')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='个人总分摊')),
                ('date', models.DateField(auto_now_add=True, verbose_name='分摊生成日期')),
                ('fee_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hostel.fee_record_one', verbose_name='对应的费用记录')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sharing_records', to='hostel.occupancyrecord', verbose_name='住宿记录')),
            ],
        ),
        migrations.CreateModel(
            name='standard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feetype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel.feetype', verbose_name='计费类型')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel.room', verbose_name='房间')),
            ],
        ),
        migrations.CreateModel(
            name='user_img',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='上传名称')),
                ('img', models.ImageField(upload_to='avatar/', verbose_name='头像')),
                ('upload_time', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('admin_img', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avatars', to='hostel.admin')),
            ],
            options={
                'verbose_name': '管理员头像',
                'ordering': ['-upload_time'],
            },
        ),
        migrations.AddField(
            model_name='person',
            name='userstatus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel.userstatus', verbose_name='用户状态'),
        ),
    ]
