# Generated by Django 5.2.4 on 2025-10-13 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='楼栋区域')),
            ],
        ),
        migrations.CreateModel(
            name='Depart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depart_title', models.CharField(max_length=50, verbose_name='部门名称')),
                ('depart_number', models.CharField(default=6, max_length=50, verbose_name='部门人数')),
            ],
        ),
        migrations.CreateModel(
            name='gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='性别')),
            ],
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='权限名称')),
            ],
        ),
        migrations.CreateModel(
            name='Personne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='人员类型')),
            ],
        ),
        migrations.CreateModel(
            name='room_status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('住满', '已满'), ('可住', '未满'), ('维修', '维修'), ('废弃/其他', '其他')], max_length=30, verbose_name='房间状态')),
            ],
        ),
        migrations.CreateModel(
            name='userstatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='用户状态')),
            ],
        ),
        migrations.CreateModel(
            name='dorm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='楼栋名称')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel.area', verbose_name='区域id')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=30, verbose_name='房间名称')),
                ('people', models.IntegerField(verbose_name='房间人数')),
                ('dorm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel.dorm', verbose_name='楼栋id')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel.gender', verbose_name='性别id')),
                ('room_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel.room_status', verbose_name='房间状态id')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='名字')),
                ('phone', models.CharField(max_length=30, verbose_name='电话号码')),
                ('depart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel.depart', verbose_name='部门')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel.gender', verbose_name='性别id')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel.permission', verbose_name='权限id')),
                ('personne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel.personne', verbose_name='人员类型id')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel.room', verbose_name='房间id')),
                ('userstatus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel.userstatus', verbose_name='用户状态id')),
            ],
        ),
        migrations.CreateModel(
            name='occupancyrecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_date', models.DateField(verbose_name='入住时间')),
                ('check_out_date', models.DateField(blank=True, null=True, verbose_name='退宿时间')),
                ('status', models.CharField(choices=[('0', '正常'), ('1', '退宿')], default='0', max_length=30, verbose_name='状态(0-正常,1-退宿)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel.person', verbose_name='员工')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel.room', verbose_name='房间id')),
            ],
        ),
    ]
