# Generated by Django 5.2.4 on 2025-10-16 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_perpe',
            field=models.CharField(default='6R', max_length=30, verbose_name='房间属性'),
        ),
    ]
