# Generated by Django 5.2.4 on 2025-12-03 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='sharing2',
            new_name='sharing',
        ),
    ]
