# Generated by Django 5.2.4 on 2025-12-03 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0002_rename_sharing2_sharing'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource_useage',
            name='date',
            field=models.CharField(default=2015, max_length=30, verbose_name='计算月份'),
            preserve_default=False,
        ),
    ]
