# Generated by Django 5.2.4 on 2025-10-16 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0002_room_room_perpe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room_status',
            name='name',
            field=models.CharField(max_length=30, verbose_name='房间状态'),
        ),
    ]
