# Generated by Django 5.2.4 on 2025-10-16 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0003_alter_room_status_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='dorm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel.dorm', verbose_name='楼栋'),
        ),
        migrations.AlterField(
            model_name='room',
            name='gender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel.gender', verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel.room_status', verbose_name='房间状态'),
        ),
    ]
