# Generated by Django 5.2.4 on 2025-12-03 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0003_resource_useage_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource_useage',
            name='date',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='计算月份'),
        ),
    ]
