# Generated by Django 5.2.4 on 2025-12-03 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0004_alter_resource_useage_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='useage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.CharField(default='89602', max_length=30, verbose_name='月初计数')),
                ('end', models.CharField(default='90002', max_length=40, verbose_name='月底计数')),
                ('usege', models.DecimalField(blank=True, decimal_places=2, max_digits=10, max_length=30, null=True, verbose_name='用量')),
                ('check_in_date', models.DateField(verbose_name='录入日期')),
                ('check_people', models.CharField(max_length=30, verbose_name='录入人')),
                ('feetype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel.feetype', verbose_name='计费类型')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='re', to='hostel.room', verbose_name='房间')),
            ],
        ),
    ]
