# Generated by Django 5.2.4 on 2025-10-20 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0004_alter_room_dorm_alter_room_gender_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='feetype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='计费项目')),
                ('fee', models.CharField(max_length=30, verbose_name='费用单价')),
                ('bit', models.CharField(max_length=30, verbose_name='计算单位')),
                ('status', models.CharField(choices=[('启用', '用'), ('封存', '封')], max_length=30, verbose_name='名字')),
                ('cdate', models.DateField(verbose_name='创建时间')),
            ],
        ),
        migrations.CreateModel(
            name='fee_record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='计算月份')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, max_length=30, verbose_name='金额')),
                ('status', models.CharField(choices=[('0', '未缴'), ('1', '已缴')], default='0', max_length=30, verbose_name='状态(0-未缴,1-已缴)')),
                ('cdate', models.DateField(verbose_name='创建时间')),
                ('check_people', models.CharField(max_length=30, verbose_name='录入人')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel.room', verbose_name='房间')),
                ('feetype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel.feetype', verbose_name='计费类型')),
            ],
        ),
        migrations.CreateModel(
            name='fee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, max_length=30, verbose_name='总金额')),
                ('paid', models.DecimalField(decimal_places=2, max_digits=10, max_length=30, verbose_name='已缴金额')),
                ('date', models.DateField(verbose_name='缴纳月份')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel.room', verbose_name='房间')),
                ('fee_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel.fee_record', verbose_name='费用记录')),
            ],
        ),
        migrations.CreateModel(
            name='feesharing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feesharing', models.CharField(max_length=30, verbose_name='个人分摊金额')),
                ('status', models.CharField(choices=[('1', '是'), ('0', '否')], max_length=30, verbose_name='是否缴纳(0-是,1-否)')),
                ('date', models.DateField(blank=True, null=True, verbose_name='缴纳时间')),
                ('fee_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel.fee_record', verbose_name='费用细则')),
                ('occupancyrecord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel.occupancyrecord', verbose_name='住宿记录')),
            ],
        ),
        migrations.CreateModel(
            name='resource_useage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='计算月份')),
                ('usege', models.DecimalField(decimal_places=2, max_digits=10, max_length=30, verbose_name='用量')),
                ('check_in_date', models.DateField(verbose_name='录入日期')),
                ('check_people', models.CharField(max_length=30, verbose_name='录入人')),
                ('feetype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel.feetype', verbose_name='计费类型')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel.room', verbose_name='房间')),
            ],
        ),
        migrations.CreateModel(
            name='standard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feetype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel.feetype', verbose_name='计费类型')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel.room', verbose_name='房间')),
            ],
        ),
    ]
