# Generated by Django 5.2.4 on 2025-10-22 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0005_feetype_fee_record_fee_feesharing_resource_useage_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feesharing',
            old_name='feesharing',
            new_name='feesharings',
        ),
        migrations.AlterField(
            model_name='feetype',
            name='status',
            field=models.CharField(choices=[('启用', '用'), ('封存', '封')], max_length=30, verbose_name='状态'),
        ),
    ]
