# Generated by Django 5.2.4 on 2025-10-22 03:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0006_rename_feesharing_feesharing_feesharings_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fee',
            name='fee_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel.fee_record', verbose_name='费用细则'),
        ),
    ]
