# Generated by Django 5.2.4 on 2025-12-04 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0006_alter_fee_record_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fee_record_one',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, max_length=30, null=True, verbose_name='总金额'),
        ),
    ]
