# Generated by Django 5.2.4 on 2025-10-22 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0007_alter_fee_fee_record'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=128, verbose_name='密码')),
                ('name', models.CharField(blank=True, max_length=30, verbose_name='真实姓名')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='邮箱')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='联系电话')),
                ('is_super', models.BooleanField(default=False, verbose_name='超级管理员')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('depart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hostel.depart', verbose_name='所属部门')),
                ('permissions', models.ManyToManyField(blank=True, to='hostel.permission', verbose_name='权限')),
            ],
            options={
                'verbose_name': '管理员',
                'verbose_name_plural': '管理员列表',
                'ordering': ['-create_date'],
            },
        ),
    ]
