# Generated by Django 5.2.4 on 2025-12-04 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0007_alter_fee_record_one_amount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='resource_useage',
        ),
    ]
