# Generated by Django 5.2.4 on 2025-10-23 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0008_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='background',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='上传名称')),
                ('img', models.FileField(max_length=128, upload_to='bg/', verbose_name='文件')),
            ],
        ),
    ]
