# Generated by Django 5.2.4 on 2025-12-05 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0008_delete_resource_useage'),
    ]

    operations = [
        migrations.CreateModel(
            name='money_upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='上传者姓名-房间号-楼栋号')),
                ('img', models.FileField(max_length=128, upload_to='money_upload/', verbose_name='文件')),
                ('is_img', models.BooleanField(default=False, verbose_name='是否激活')),
            ],
        ),
        migrations.AlterModelOptions(
            name='feetype',
            options={'ordering': ['-cdate', 'area', 'name'], 'verbose_name': '计费项目', 'verbose_name_plural': '计费项目管理'},
        ),
    ]
