# Generated by Django 5.2.4 on 2025-10-23 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0009_background'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource_useage',
            name='usege',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, max_length=30, null=True, verbose_name='用量'),
        ),
    ]
