# Generated by Django 5.2.4 on 2025-12-08 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0009_money_upload_alter_feetype_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fee_record_one',
            options={'ordering': ['-date', 'room'], 'verbose_name': '费用记录', 'verbose_name_plural': '费用记录管理'},
        ),
        migrations.AddField(
            model_name='occupancyrecord',
            name='discount',
            field=models.BooleanField(default=True, verbose_name='是否优惠'),
        ),
        migrations.AlterUniqueTogether(
            name='fee_record_one',
            unique_together={('room', 'date')},
        ),
    ]
