# Generated by Django 5.2.4 on 2025-12-08 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0010_alter_fee_record_one_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='check_in_date',
            field=models.DateField(default='2025-10-01', verbose_name='生效日期'),
        ),
        migrations.AddField(
            model_name='discount',
            name='date_nums',
            field=models.CharField(default='180', max_length=30, verbose_name='生效天数'),
        ),
    ]
