# Generated by Django 5.2.4 on 2025-10-23 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0011_alter_resource_useage_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fee_record',
            name='date',
            field=models.CharField(max_length=30, verbose_name='计算月份'),
        ),
    ]
