# Generated by Django 5.2.4 on 2025-12-08 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0011_discount_check_in_date_discount_date_nums'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='status',
            field=models.BooleanField(default=True, verbose_name='是否启用'),
        ),
    ]
