# Generated by Django 5.2.4 on 2025-12-09 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0012_discount_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='room_type',
            name='money',
            field=models.DecimalField(decimal_places=2, default=1500, max_digits=10, max_length=30, verbose_name='房间单价'),
            preserve_default=False,
        ),
    ]
