# Generated by Django 5.2.4 on 2025-10-23 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0012_alter_fee_record_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='feesharing',
            name='fee_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hostel.feetype', verbose_name='计费类型'),
        ),
    ]
