# Generated by Django 5.2.4 on 2025-10-28 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0013_feesharing_fee_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_img',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='上传名称')),
                ('upload_time', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('admin_img', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avatar', to='hostel.admin')),
            ],
            options={
                'verbose_name': '管理员头像',
                'ordering': ['-upload_time'],
            },
        ),
    ]
