# Generated by Django 5.2.4 on 2025-12-09 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0013_room_type_money'),
    ]

    operations = [
        migrations.AddField(
            model_name='room_type',
            name='cdate',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='创建时间'),
        ),
    ]
