# Generated by Django 5.2.4 on 2025-12-09 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0014_room_type_cdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='room_type',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hostel.area', verbose_name='区域'),
        ),
    ]
