# Generated by Django 5.2.4 on 2025-10-28 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0014_user_img'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user_img',
        ),
    ]
