# Generated by Django 5.2.4 on 2025-12-10 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0015_room_type_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='room_type',
            name='status',
            field=models.BooleanField(default=True, verbose_name='是否启用'),
        ),
    ]
