# Generated by Django 5.2.4 on 2025-12-10 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0016_room_type_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='fee_record_one',
            name='room_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, max_length=30, null=True, verbose_name='房费'),
        ),
    ]
