# Generated by Django 5.2.4 on 2025-10-29 03:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0016_user_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fee',
            name='fee_record',
        ),
        migrations.AlterField(
            model_name='user_img',
            name='admin_img',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avatars', to='hostel.admin'),
        ),
    ]
