# Generated by Django 5.2.4 on 2025-12-10 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0017_fee_record_one_room_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharing',
            name='ketizu_money',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='课题组应补贴金额'),
        ),
        migrations.AddField(
            model_name='sharing',
            name='yuan_money',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='院级应补贴金额'),
        ),
    ]
