# Generated by Django 5.2.4 on 2025-10-29 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0017_remove_fee_fee_record_alter_user_img_admin_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='fee',
            name='status',
            field=models.CharField(choices=[('1', '是'), ('0', '否')], default=1, max_length=30, verbose_name='是否缴纳(0-是,1-否)'),
        ),
    ]
