# Generated by Django 5.2.4 on 2025-10-29 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0018_fee_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='background',
            name='is_img',
            field=models.BooleanField(default=False, verbose_name='是否激活'),
        ),
        migrations.AlterField(
            model_name='background',
            name='img',
            field=models.FileField(max_length=128, upload_to='backgrounds/', verbose_name='文件'),
        ),
    ]
