# Generated by Django 5.2.4 on 2025-12-10 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0018_sharing_ketizu_money_sharing_yuan_money'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharing',
            name='room_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='房费'),
        ),
    ]
