# Generated by Django 5.2.4 on 2025-10-30 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0019_background_is_img_alter_background_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='a_img',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_img', models.ImageField(upload_to='admin_img/', verbose_name='头像')),
                ('is_img', models.BooleanField(default=False, verbose_name='是否启用')),
            ],
        ),
    ]
