# Generated by Django 5.2.4 on 2025-12-11 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0019_sharing_room_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharing',
            name='date',
            field=models.DateField(verbose_name='分摊生成日期'),
        ),
    ]
