# Generated by Django 5.2.4 on 2025-10-31 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0020_a_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='is_super',
            field=models.BooleanField(default=False, verbose_name='是否超级管理员'),
        ),
        migrations.AlterField(
            model_name='admin',
            name='password',
            field=models.CharField(max_length=128, verbose_name='初始密码'),
        ),
    ]
