# Generated by Django 5.2.4 on 2025-12-12 01:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0020_alter_sharing_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feetype',
            options={},
        ),
        migrations.AlterModelOptions(
            name='room_type',
            options={'ordering': ['-cdate'], 'verbose_name': '房间类型', 'verbose_name_plural': '房间类型管理'},
        ),
        migrations.AlterField(
            model_name='room_type',
            name='cdate',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2025, 12, 12, 1, 46, 25, 653828, tzinfo=datetime.timezone.utc), verbose_name='创建时间'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='room_type',
            unique_together={('area', 'name')},
        ),
        migrations.DeleteModel(
            name='standard',
        ),
    ]
