# Generated by Django 5.2.4 on 2025-10-31 02:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0021_alter_admin_is_super_alter_admin_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='username',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='permissions',
        ),
        migrations.AddField(
            model_name='admin',
            name='permissions',
            field=models.ForeignKey(blank=True, default=3, on_delete=django.db.models.deletion.CASCADE, to='hostel.permission', verbose_name='权限'),
            preserve_default=False,
        ),
    ]
