# Generated by Django 5.2.4 on 2025-12-12 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0021_alter_feetype_options_alter_room_type_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feesharing',
            name='fee_record',
        ),
        migrations.RemoveField(
            model_name='feesharing',
            name='fee_type',
        ),
        migrations.RemoveField(
            model_name='feesharing',
            name='occupancyrecord',
        ),
        migrations.DeleteModel(
            name='fee_record',
        ),
        migrations.DeleteModel(
            name='feesharing',
        ),
    ]
