# Generated by Django 5.2.4 on 2025-10-31 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0022_remove_admin_username_remove_admin_permissions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel.gender', verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='person',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel.permission', verbose_name='权限'),
        ),
        migrations.AlterField(
            model_name='person',
            name='personne',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel.personne', verbose_name='人员类型'),
        ),
        migrations.AlterField(
            model_name='person',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel.room', verbose_name='房间'),
        ),
        migrations.AlterField(
            model_name='person',
            name='userstatus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel.userstatus', verbose_name='用户状态'),
        ),
    ]
