# Generated by Django 5.2.4 on 2025-12-12 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0022_remove_feesharing_fee_record_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fee_record_one',
            name='date',
            field=models.DateField(verbose_name='计算月份'),
        ),
    ]
