# Generated by Django 5.2.4 on 2025-11-04 08:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0023_alter_person_gender_alter_person_permission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feesharing',
            name='end_date',
            field=models.DateField(default=datetime.date(2025, 7, 5), verbose_name='结束计费日期'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feesharing',
            name='start_date',
            field=models.DateField(default=datetime.date(2025, 6, 5), verbose_name='开始计费日期'),
            preserve_default=False,
        ),
    ]
