# Generated by Django 5.2.4 on 2025-12-12 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0023_alter_fee_record_one_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room_type',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='room_type',
            unique_together=set(),
        ),
    ]
