# Generated by Django 5.2.4 on 2025-12-12 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0024_alter_room_type_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room_type',
            options={'ordering': ['area', 'name', '-cdate'], 'verbose_name': '房间类型', 'verbose_name_plural': '房间类型管理'},
        ),
        migrations.AlterField(
            model_name='room',
            name='people',
            field=models.IntegerField(default=0, verbose_name='房间人数'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hostel.room_status', verbose_name='房间状态'),
        ),
    ]
