# Generated by Django 5.2.4 on 2025-11-06 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0024_feesharing_end_date_feesharing_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feesharing',
            name='status',
            field=models.CharField(choices=[('1', '是'), ('0', '否')], max_length=30, verbose_name='是否缴纳(1-是)'),
        ),
    ]
