# Generated by Django 5.2.4 on 2025-12-14 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0025_alter_room_type_options_alter_room_people_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feetype',
            options={'ordering': ['area', 'name', '-cdate'], 'verbose_name': '计费项目', 'verbose_name_plural': '计费项目管理'},
        ),
        migrations.AddField(
            model_name='feetype',
            name='effective_date',
            field=models.DateField(blank=True, null=True, verbose_name='生效日期'),
        ),
        migrations.AddField(
            model_name='room_type',
            name='effective_date',
            field=models.DateField(blank=True, null=True, verbose_name='生效日期'),
        ),
    ]
