# Generated by Django 5.2.4 on 2025-11-06 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0026_alter_fee_record_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fee_record',
            name='status',
            field=models.CharField(choices=[('0', '未缴'), ('1', '已缴'), ('2', '部分已缴')], default='0', max_length=30, verbose_name='状态(0-未缴,1-已缴,2-部分已缴)'),
        ),
    ]
