# Generated by Django 5.2.4 on 2025-12-15 00:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0026_alter_feetype_options_feetype_effective_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hostel.room', verbose_name='房间'),
        ),
    ]
