# Generated by Django 5.2.4 on 2025-12-15 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0027_alter_person_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='occupancyrecord',
            name='date_limit',
            field=models.CharField(default='180', max_length=30, verbose_name='生效天数'),
        ),
    ]
