# Generated by Django 5.2.4 on 2025-11-06 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0027_alter_fee_record_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='password',
            field=models.CharField(default='123456', max_length=30, verbose_name='初始密码'),
            preserve_default=False,
        ),
    ]
