# Generated by Django 5.2.4 on 2025-12-15 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0028_occupancyrecord_date_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occupancyrecord',
            name='date_limit',
            field=models.CharField(default='180', max_length=30, verbose_name='优惠生效天数'),
        ),
    ]
