# Generated by Django 5.2.4 on 2025-11-10 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0028_person_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fee_record',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='hostel.room', verbose_name='房间'),
        ),
        migrations.AlterField(
            model_name='resource_useage',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='res', to='hostel.room', verbose_name='房间'),
        ),
        migrations.CreateModel(
            name='sharing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cold', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='水费分摊费用')),
                ('water', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='水费分摊费用')),
                ('power', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='电费分摊费用')),
                ('home', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='房费分摊费用')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_name', to='hostel.occupancyrecord')),
            ],
        ),
    ]
