# Generated by Django 5.2.4 on 2025-12-15 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0029_alter_occupancyrecord_date_limit'),
    ]

    operations = [
        migrations.CreateModel(
            name='discount_feetype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='折扣名称')),
            ],
        ),
    ]
