# Generated by Django 5.2.4 on 2025-11-12 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0029_alter_fee_record_room_alter_resource_useage_room_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='password',
            field=models.CharField(max_length=128, verbose_name='初始密码'),
        ),
    ]
