# Generated by Django 5.2.4 on 2025-12-15 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0030_discount_feetype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='fee_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel.discount_feetype', verbose_name='折扣的费用类型'),
        ),
    ]
