# Generated by Django 5.2.4 on 2025-11-14 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0030_alter_person_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharing',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=225.25, max_digits=10, max_length=30, verbose_name='总费用分摊'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='fee_record_one',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cold', models.DecimalField(decimal_places=2, max_digits=10, max_length=30, verbose_name='空调费')),
                ('power', models.DecimalField(decimal_places=2, max_digits=10, max_length=30, verbose_name='电费')),
                ('water', models.DecimalField(decimal_places=2, max_digits=10, max_length=30, verbose_name='水费')),
                ('home', models.DecimalField(decimal_places=2, max_digits=10, max_length=30, verbose_name='房费')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, max_length=30, verbose_name='总金额')),
                ('status', models.CharField(choices=[('0', '未缴'), ('1', '已缴'), ('2', '部分已缴')], default='0', max_length=30, verbose_name='状态(0-未缴,1-已缴,2-部分已缴)')),
                ('date', models.CharField(max_length=30, verbose_name='计算月份')),
                ('check_people', models.CharField(max_length=30, verbose_name='录入人')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel.room', verbose_name='房间')),
            ],
        ),
    ]
