# Generated by Django 5.2.4 on 2025-12-15 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0031_alter_discount_fee_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='rate',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='折扣率(0-1之间)'),
        ),
    ]
