# Generated by Django 5.2.4 on 2025-11-14 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0031_sharing_amount_fee_record_one'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fee_record_one',
            name='check_people',
            field=models.CharField(default='admin', max_length=30, verbose_name='录入人'),
        ),
    ]
