# Generated by Django 5.2.4 on 2025-12-15 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0032_alter_discount_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='date',
            field=models.CharField(max_length=30, verbose_name='创建月份'),
        ),
    ]
