# Generated by Django 5.2.4 on 2025-11-14 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0032_alter_fee_record_one_check_people'),
    ]

    operations = [
        migrations.CreateModel(
            name='discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.CharField(max_length=30, verbose_name='折扣率')),
                ('fee_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel.feetype', verbose_name='费用类型')),
            ],
        ),
    ]
