# Generated by Django 5.2.4 on 2025-11-18 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0033_discount'),
    ]

    operations = [
        migrations.CreateModel(
            name='room_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='房间类型')),
                ('nums', models.CharField(default='21', max_length=30, verbose_name='房间数量')),
                ('bed_count', models.IntegerField(verbose_name='床位数量')),
            ],
        ),
    ]
