# Generated by Django 5.2.4 on 2025-12-15 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0033_alter_discount_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='date_nums',
        ),
    ]
