# Generated by Django 5.2.4 on 2025-12-15 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0034_remove_discount_date_nums'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room_type',
            options={'ordering': ['dorm', 'name', '-cdate'], 'verbose_name': '房间类型', 'verbose_name_plural': '房间类型管理'},
        ),
        migrations.RemoveField(
            model_name='room_type',
            name='area',
        ),
        migrations.AddField(
            model_name='room_type',
            name='dorm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hostel.dorm', verbose_name='区域'),
        ),
    ]
