# Generated by Django 5.2.4 on 2025-11-18 06:59

from django.db import migrations
from hostel import models

def map_old_to_new(apps, schema_editor):
    # 获取模型（注意：必须用 apps.get_model，不能直接导入）
    Room = apps.get_model('hostel', 'Room')
    RoomType = apps.get_model('hostel', 'room_type')
    
    # 遍历所有房间，将 room_perpe 映射到 room_type
    for room in Room.objects.all():
        try:
            # 核心逻辑：根据 room_perpe 匹配 room_type.name（需手动对应规则）
            # 示例规则：'6R' 对应 '6人间'，'4R' 对应 '4人间'，以此类推
            type_map = {
                '6R': '6人间',
                '4R': '4人间',
                '1R': '单人间',
                '8R': '8人间',  # 你的数据中有 8R，需确保 room_type 表有对应记录
            }
            room_type_name = type_map.get(room.room_perpe, '6人间')  # 默认值为 6人间
            room_type = RoomType.objects.get(name=room_type_name)
            
            # 赋值新外键
            room.room_type = room_type
            room.save()
        except RoomType.DoesNotExist:
            # 若 room_type 表中没有对应记录，创建一个（或设为默认）
            room_type, created = RoomType.objects.get_or_create(
                name=room_type_name,
                defaults={
                    'bed_count': int(room.room_perpe.replace('R', '')),  # 如 '6R' → 6
                    'nums': '21'  # 默认房间数量，可根据需求调整
                }
            )
            room.room_type = room_type
            room.save()

class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0035_room_room_type'),
    ]

    operations = [
         migrations.RunPython(map_old_to_new),
    ]
