# Generated by Django 5.2.4 on 2025-11-18 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0036_map_room_perpe_to_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='room_type',
        ),
    ]
