# Generated by Django 5.2.4 on 2025-11-18 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0038_room_room_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='room_perpe',
        ),
    ]
