# Generated by Django 5.2.4 on 2025-11-18 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0039_remove_room_room_perpe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room_type',
            name='nums',
        ),
    ]
